# Generated by Django 3.0.2 on 2020-02-29 12:14

from django.db import migrations, models
import urlshorter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default=urlshorter.models.code_gen, max_length=5)),
                ('notshorter_url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('clicks', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['clicks'],
            },
        ),
    ]
